name: library release
on: #监听的事件和分支配置
  push:
    tags:
      - 'v*'
# enter to workflows
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm publish # 如果发布之前需要构建，可添加prepublishOnly的生命周期脚本
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 上面在Github Secrets中设置的密钥
  # github-release:
  #   needs: publish
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Setup node ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       registry-url: https://registry.npmjs.org/
  #   - run: npm i -g github-release-from-changelog
  #   - run: github-release-from-changelog
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
